name: Snyk scheduled test
on:
  schedule:
    - cron: '0 2 * * 1'
  push:
    branches:
      - master

jobs:
  security:
    runs-on: ubuntu-latest
    env:
      REPORT_FILE: test.json

    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master
        with:
          snyk-version: v1.1032.0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Decrypt libraries
        run: ./.github/scripts/decrypt_libraries.sh
        env:
          E4LINK_PASSPHRASE: ${{ secrets.E4LINK_PASSPHRASE }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: >
          snyk test
          --all-sub-projects
          --configuration-matching='^releaseRuntimeClasspath$'
          --fail-on=upgradable
          --json-file-output=${{ env.REPORT_FILE }}
          --org=radar-base
          --policy-path=$PWD/.snyk

      - name: Report new vulnerabilities
        uses: thehyve/report-vulnerability@master
        if: success() || failure()
        with:
          report-file: ${{ env.REPORT_FILE }}
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
